export const sections = [
    { path: '/', id: 'inicio' },
    { path: '/ahorradores_inversionistas/', id: 'productos-servicios' },
    { path: '/business-people/', id: 'productos-servicios' },
    { path: '/informacion-al-consumidor-financiero/', id: 'productos-servicios' },
    { path: '/seguros/', id: 'productos-servicios' },
    { path: '/giros-internacionales/', id: 'productos-servicios' },
    { path: '/trabaja-con-nosotros/', id: 'nosotros' },
    { path: '/quienes-somos/', id: 'nosotros' },
    { path: '/proteccion-y-sostenibilidad/', id: 'nosotros' },
    { path: '/licitaciones/', id: 'nosotros' },
    { path: '/fundacion-wwb/', id: 'nosotros' },
    { path: '/estados-financieros/', id: 'atencion-inversionista' },
    { path: '/atencion-inversionista/', id: 'atencion-inversionista' },
    { path: '/info-accionistas/', id: 'atencion-inversionista' },
    { path: '/junta-directiva-alta-gerencia/', id: 'atencion-inversionista' },
    { path: '/pqrs/', id: 'canales-atencion' },
    { path: '/atencion_financiero/', id: 'canales-atencion' },
]